"""symbols schema all

Revision ID: 3c91c8c3a66d
Revises: dea20f06d137
Create Date: 2025-04-07 20:10:56.497298

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = '3c91c8c3a66d'
down_revision: Union[str, None] = 'dea20f06d137'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('DTN_IQFEED_SYMBOLS_ALL',
    sa.Column('created_at', sa.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('symbol', sa.String(length=255), nullable=False),
    sa.Column('description', sa.String(length=255), nullable=False),
    sa.Column('security_type', sa.String(length=255), nullable=False),
    sa.Column('exchange', sa.String(length=255), nullable=False),
    sa.Column('listed_market', sa.String(length=255), nullable=False),
    sa.PrimaryKeyConstraint('symbol')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    op.drop_table('DTN_IQFEED_SYMBOLS_ALL')
    # ### end Alembic commands ###
