"""symbols metadata

Revision ID: 8487af036e95
Revises: 3c91c8c3a66d
Create Date: 2025-04-08 17:45:55.245033

"""

from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = "8487af036e95"
down_revision: Union[str, None] = "3c91c8c3a66d"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "DTN_SYMBOLS_META",
        sa.Column(
            "created_at",
            sa.TIMESTAMP(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.TIMESTAMP(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("symbol", sa.String(length=255), nullable=False),
        sa.Column("count", sa.Integer(), nullable=False),
        sa.Column("status", sa.String(length=255), nullable=True),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "IQFEED_READY_META_DATA",
        sa.Column(
            "created_at",
            sa.TIMESTAMP(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.TIMESTAMP(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("symbol", sa.String(length=255), nullable=False),
        sa.Column("count", sa.Integer(), nullable=False),
        sa.Column(
            "last_record_datetime",
            sa.TIMESTAMP(timezone=True),
            nullable=False,
        ),
        sa.Column("status", sa.String(length=255), nullable=True),
        sa.Column("max_high", sa.Float(), nullable=False),
        sa.Column("min_low", sa.Float(), nullable=False),
        sa.Column("total_volume", sa.Integer(), nullable=False),
        sa.Column("average_close", sa.Float(), nullable=False),
        sa.Column(
            "last_processed_period", sa.String(length=255), nullable=False
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("IQFEED_READY_META_DATA")
    op.drop_table("DTN_SYMBOLS_META")
    # ### end Alembic commands ###
