"""history_completion

Revision ID: 8710ec90361a
Revises: 21dc98c4ce6f
Create Date: 2025-04-15 16:40:12.733043

"""

from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = "8710ec90361a"
down_revision: Union[str, None] = "21dc98c4ce6f"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "ticker_progress",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("ticker", sa.String(length=20), nullable=False),
        sa.Column("start_date", sa.DateTime(), nullable=False),
        sa.Column("end_date", sa.DateTime(), nullable=False),
        sa.Column("interval", sa.String(length=20), nullable=False),
        sa.Column("extraction_date", sa.Date(), nullable=False),
        sa.Column("successful", sa.Boolean(), nullable=True),
        sa.Column("record_count", sa.Integer(), nullable=True),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_ticker_progress_ticker"),
        "ticker_progress",
        ["ticker"],
        unique=False,
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(
        op.f("ix_ticker_progress_ticker"), table_name="ticker_progress"
    )
    op.drop_table("ticker_progress")
    # ### end Alembic commands ###
