"""symbols schema

Revision ID: dea20f06d137
Revises:
Create Date: 2025-04-07 19:49:26.375543

"""

from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "dea20f06d137"
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "DTN_IQFEED_SYMBOLS_CONTINUOUS_CONTRACTS_FUTURES",
        sa.Column(
            "created_at",
            sa.TIMESTAMP(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.TIMESTAMP(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("symbol", sa.String(length=255), nullable=False),
        sa.Column("description", sa.String(length=255), nullable=False),
        sa.Column("security_type", sa.String(length=255), nullable=False),
        sa.Column("exchange", sa.String(length=255), nullable=False),
        sa.Column("listed_market", sa.String(length=255), nullable=False),
        sa.PrimaryKeyConstraint("symbol"),
    )
    op.create_table(
        "DTN_IQFEED_SYMBOLS_EMINIS",
        sa.Column(
            "created_at",
            sa.TIMESTAMP(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.TIMESTAMP(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("symbol", sa.String(length=255), nullable=False),
        sa.Column("description", sa.String(length=255), nullable=False),
        sa.Column("security_type", sa.String(length=255), nullable=False),
        sa.Column("exchange", sa.String(length=255), nullable=False),
        sa.Column("listed_market", sa.String(length=255), nullable=False),
        sa.PrimaryKeyConstraint("symbol"),
    )
    op.create_table(
        "DTN_IQFEED_SYMBOLS_FRONT_MONTH_FUTURES",
        sa.Column(
            "created_at",
            sa.TIMESTAMP(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.TIMESTAMP(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("symbol", sa.String(length=255), nullable=False),
        sa.Column("description", sa.String(length=255), nullable=False),
        sa.Column("security_type", sa.String(length=255), nullable=False),
        sa.Column("exchange", sa.String(length=255), nullable=False),
        sa.Column("listed_market", sa.String(length=255), nullable=False),
        sa.PrimaryKeyConstraint("symbol"),
    )
    op.create_table(
        "DTN_IQFEED_SYMBOLS_NO_OPTIONS",
        sa.Column(
            "created_at",
            sa.TIMESTAMP(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.TIMESTAMP(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("symbol", sa.String(length=255), nullable=False),
        sa.Column("description", sa.String(length=255), nullable=False),
        sa.Column("security_type", sa.String(length=255), nullable=False),
        sa.Column("exchange", sa.String(length=255), nullable=False),
        sa.Column("listed_market", sa.String(length=255), nullable=False),
        sa.PrimaryKeyConstraint("symbol"),
    )
    op.create_table(
        "DTN_IQFEED_SYMBOLS_NO_SPREADS",
        sa.Column(
            "created_at",
            sa.TIMESTAMP(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.TIMESTAMP(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("symbol", sa.String(length=255), nullable=False),
        sa.Column("description", sa.String(length=255), nullable=False),
        sa.Column("security_type", sa.String(length=255), nullable=False),
        sa.Column("exchange", sa.String(length=255), nullable=False),
        sa.Column("listed_market", sa.String(length=255), nullable=False),
        sa.PrimaryKeyConstraint("symbol"),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("DTN_IQFEED_SYMBOLS_NO_SPREADS")
    op.drop_table("DTN_IQFEED_SYMBOLS_NO_OPTIONS")
    op.drop_table("DTN_IQFEED_SYMBOLS_FRONT_MONTH_FUTURES")
    op.drop_table("DTN_IQFEED_SYMBOLS_EMINIS")
    op.drop_table("DTN_IQFEED_SYMBOLS_CONTINUOUS_CONTRACTS_FUTURES")
    # ### end Alembic commands ###
